version: '3.9'

services:
  admin:
    image: xuxueli/xxl-job-admin:2.4.0
    container_name: xxl_job_admin
    restart: always
    hostname: admin
    ports:
      - "7070:8080"
    links:
      - mysql
    volumes:
      - ./data/logs:/data/applogs
      - ./data/xxl-job/:/xxl-job
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Shanghai
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - mysql
    networks:
      - xxl_job_net

  mysql:
    image: mysql:8
    restart: always
    hostname: mysql
    container_name: xxl_job_db
    ports:
      - "13306:3306"
    volumes:
      #      #mysql数据库挂载到host物理机目录/e/docker/mysql/data/db
      #      - "./data:/var/lib/mysql"
      #      #容器的配置目录挂载到host物理机目录/e/docker/mysql/data/conf
      #      - "./conf:/etc/mysql/conf.d"
      #      - "./root:/root"
      - "./sql:/docker-entrypoint-initdb.d"
    environment:
      TZ: Asia/Shanghai
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: 123456 #root管理员用户密码
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    networks:
      - xxl_job_net
networks:
  xxl_job_net:
    driver: bridge